extends: default

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: -1
    min-spaces-inside: -1
  brackets:
    max-spaces-inside: -1
    min-spaces-inside: -1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  quoted-strings: disable
  document-start: disable

ignore: |
  agent/helm/*/templates/
  agent/helm/*/.helmignore
    