{{- if and (eq (include "matillion-runner.cloudProvider" .) "aws") (eq (include "matillion-runner.aws.credentialSource" .) "static") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matillion-runner.fullname" . }}-aws-local
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  aws-region: {{ .Values.aws.local.region | b64enc }}
  aws-access-key-id: {{ .Values.aws.local.accessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.aws.local.secretAccessKey | b64enc }}
{{- end }}