---
{{- if .Values.queueAdapter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matillion-runner.fullname" . }}-queue-adapter-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "queueAdapter.serviceAccount.clientId is required when queueAdapter.enabled" .Values.queueAdapter.serviceAccount.clientId }}
  labels:
{{- include "matillion-runner.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
{{- end }}
