---
{{- if .Values.scriptRunner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matillion-runner.scriptRunner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "matillion-runner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "matillion-runner.scriptRunner.fullname" . }}-pods
{{- include "matillion-runner.scriptRunner.selectorLabels" . | nindent 4 }}
  ports:
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: ssh
{{- end }}
